#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${TENANT_MANAGEMENT_DB_USERNAME}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${TENANT_MANAGEMENT_DB_USERNAME}', '${TENANT_MANAGEMENT_DB_PASSWORD}');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${KEYCLOAK_DB_USERNAME}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${KEYCLOAK_DB_USERNAME}', '${KEYCLOAK_DB_PASSWORD}');
  END IF;
END
\$\$;

SELECT format('CREATE DATABASE %I OWNER %I', '${TENANT_MANAGEMENT_DB}', '${TENANT_MANAGEMENT_DB_USERNAME}')
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = '${TENANT_MANAGEMENT_DB}'
)\gexec

SELECT format('CREATE DATABASE %I OWNER %I', '${KEYCLOAK_DB}', '${KEYCLOAK_DB_USERNAME}')
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = '${KEYCLOAK_DB}'
)\gexec
EOSQL
