#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${IAM_PROVISIONING_DB_USERNAME}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${IAM_PROVISIONING_DB_USERNAME}', '${IAM_PROVISIONING_DB_PASSWORD}');
  END IF;
END
\$\$;

SELECT format('CREATE DATABASE %I OWNER %I', '${IAM_PROVISIONING_DB}', '${IAM_PROVISIONING_DB_USERNAME}')
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = '${IAM_PROVISIONING_DB}'
)\gexec
EOSQL